name: 'Execute'

on:
  push

# Required for secrets.GITHUB_TOKEN
permissions:
  packages: write
  contents: read

env:
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: pnpm install --frozen-lockfile
      - run: pnpm start